### ISSUE TITLE
Credentials comparison is vulnerable to timing attack

### ISSUE THREAD

**Issue by Maxxxxxx-x** [JacobLinCool/hermes-mail-service#24]
### Issue
The method used to compare the user input key and the MAIN_KEY is vulnerable to timing attacks

### Code snippet
```ts
if (key !== KEY) {
    throw error(401, await $t("errors.invalid-main-key"));
}
```

### Files with this issue
[api/keys/+server.ts](https://github.com/JacobLinCool/hermes-mail-service/blob/main/src/routes/api/keys/%2Bserver.ts)

[api/key/[id]/+server.ts](https://github.com/JacobLinCool/hermes-mail-service/blob/main/src/routes/api/key/%5Bid%5D/%2Bserver.ts) 

[api/key/+server.ts](https://github.com/JacobLinCool/hermes-mail-service/blob/main/src/routes/api/key/%2Bserver.ts)

### Solution
using [timingSafeEqual](https://developers.cloudflare.com/workers/runtime-apis/web-crypto/#timingsafeequal)

**Comment by JacobLinCool** [comment]
Hi @Maxxxxxx-x, thank you for your suggestion. However, I don't believe a timing attack could be applicable in this situation, particularly given that network latency plays a significant role in the scenario. As you've noted, all affected files/actions are exposed through the HTTP API.

While the use of `timingSafeEqual` as you've recommended might theoretically solve the issue, I doubt its practical effectiveness. Besides, `timingSafeEqual` is not part of the standard Web Crypto API, which could potentially reduce code portability and introduce unnecessary complexity.

Nonetheless, I'm not a security domain expert. Therefore, I would appreciate further input from you or anyone else on this matter.

**Comment by Maxxxxxx-x** [comment]
Hi, thanks for your feedback on this issue.

While it is often considered that timing attack is impractical due to the network latency, it is possible as an attack could utilize the 
[TCP timestamp](https://stackoverflow.com/questions/7880383/what-benefit-is-conferred-by-tcp-timestamp) encoded into the TCP header to perform a timing attack. Some attack methods also tries to figure out the time required to perform the string comparisons by averaging the result to try and minimize the effects of network latency.

As for ``timingSafeEqual`` not being part of the standard Web Crypto API, I do agree that it would reduce code portability. However, I think that until ``timingSafeEual`` is implemented into Web Crypto, we could probably use something like
```ts
function timingSafeEqual(a : string, b : string) : boolean {
    let StrA = String(a);
    let StrB = String(b);
    let Flags = 0;
    
    if (StrA.length != StrB.length) {
        StrB = StrA;
        Flags = 1;
    }
    for (let i = 0; i < StrA.length; i++) {
        Flags |= (StrA.charCodeAt(i) ^ StrB.charCodeAt(i));
    }
    return Flags === 0;
}
```
